(function(){
	feature('Example feature: As a user of cucumber.js\n'+
'I want to have documentation on cucumber\n'+
'So that I can concentrate on building awesome applications')
		.scenario('Reading documentation')
			.given ('I do truc', [])
			.then ('Machin', [])
			.given ('I am on the Cucumber.js GitHub repository', [])
			.given ('there are users:', [{"username":"everzet","password":"123456","email":"everzet@knplabs.com"},{"username":"fabpot","password":"22@222","email":"fabpot@symfony.com"}])
			.when ('I go to the README file', [])
			.then ('I should see "Usage" as the page title', [])
		.scenario('controlling order (TestSet 1)')
			.given ('I do truc', [])
			.then ('Machin', [])
			.given ('there are 12 cucumbers', [])
			.when ('I eat 5 cucumbers', [])
			.then ('I should have 7 cucumbers', [])
		.scenario('controlling order (TestSet 2)')
			.given ('I do truc', [])
			.then ('Machin', [])
			.given ('there are 1 cucumbers', [])
			.when ('I eat 1 cucumbers', [])
			.then ('I should have 0 cucumbers', [])
		.scenario('controlling order (TestSet 3)')
			.given ('I do truc', [])
			.then ('Machin', [])
			.given ('there are 10 cucumbers', [])
			.when ('I eat 5 cucumbers', [])
			.then ('I should have 5 cucumbers', [])
		.scenario('controlling order (TestSet 4)')
			.given ('I do truc', [])
			.then ('Machin', [])
			.given ('there are 1 cucumbers', [])
			.when ('I eat 9 cucumbers', [])
			.then ('I should have -8 cucumbers', [])
})();