(function(){
	feature('Préciser la tranche de revenu, US01-Sélectionner la tranche revenu du client: En tant que Distributeur,\n'+
'Je dois saisir l\'estimation des revenus mensuels nets de mon client,\n'+
'Afin d\'être conforme à la loi sur la Lutte Contre le Blanchiment (LCB-FT).')
		.scenario('Visualisation de revenus')
			.given ('Je suis sur l\'écran "Connaissance Client", "5 Profession", "Vos revenus"')
			.when ('Je sélectionne la tranche de revenus')
			.then ('Je dispose de deux champs', [{"Nom du champ":"Revenus mensuels net *","Valeur par défaut":"Choisir un revenu mensuel net"},{"Nom du champ":"Préciser (€)","Valeur par défaut":"Vide"}])
			.and ('La liste des revenus apparaît dans l\'ordre suivant', [{"Revenus":"Choisir un revenu mensuel net"},{"Revenus":"Moins de 1500€"},{"Revenus":"Entre 1500€ et 2500€"},{"Revenus":"Entre 2500€ et 5000€"},{"Revenus":"Entre 5000€ et 10000€"},{"Revenus":"Plus de 10000€"}])
		.scenario('Saisie de revenus')
			.given ('Je suis sur l\'écran "Connaissance Client", "5 Profession", "Vos revenus"')
			.when ('Je renseigne les valeurs suivantes', [{"Revenus mensuels net *":"Moins de 1500€","Préciser (€)":"1200"},{"Revenus mensuels net *":"Moins de 1500€","Préciser (€)":""},{"Revenus mensuels net *":"Entre 1500€ et 2500€","Préciser (€)":"1700"},{"Revenus mensuels net *":"Entre 1500€ et 2500€","Préciser (€)":""},{"Revenus mensuels net *":"Entre 2500€ et 5000€","Préciser (€)":"5000"},{"Revenus mensuels net *":"Entre 2500€ et 5000€","Préciser (€)":""},{"Revenus mensuels net *":"Entre 5000€ et 10000€","Préciser (€)":"5001"},{"Revenus mensuels net *":"Entre 5000€ et 10000€","Préciser (€)":""},{"Revenus mensuels net *":"Plus de 10000€","Préciser (€)":"123456789"}])
			.then ('La saisie est possible')
		.scenario('Saisie incohérente de revenus')
			.given ('Je suis sur l\'écran "Connaissance Client", "5 Profession", "Vos revenus"')
			.when ('Je renseigne les valeurs suivantes', [{"Revenus mensuels net *":"Choisir un revenu mensuel net","Préciser (€)":"","message":"Champ obligatoire Revenus mensuels net"},{"Revenus mensuels net *":"Choisir un revenu mensuel net","Préciser (€)":"12000","message":"Champ obligatoire Revenus mensuels net"},{"Revenus mensuels net *":"Entre 1500€ et 2500€","Préciser (€)":"0","message":"Champ en erreur"},{"Revenus mensuels net *":"Entre 2500€ et 5000€","Préciser (€)":"1000","message":"Champ en erreur"},{"Revenus mensuels net *":"Plus de 10000€","Préciser (€)":"1234567891","message":"Champ en erreur"},{"Revenus mensuels net *":"Moins de 1500€","Préciser (€)":"-500","message":"Champ en erreur"},{"Revenus mensuels net *":"Moins de 1500€","Préciser (€)":"10^3","message":"Champ en erreur"},{"Revenus mensuels net *":"Entre 5000€ et 10000€","Préciser (€)":"fdsfuiosdfisxudf","message":"Champ en erreur"},{"Revenus mensuels net *":"Entre 5000€ et 10000€","Préciser (€)":"ff","message":"Champ en erreur"},{"Revenus mensuels net *":"Moins de 1500€","Préciser (€)":"\" \"","message":"Champ en erreur"},{"Revenus mensuels net *":"Entre 1500€ et 2500€","Préciser (€)":"%","message":"Champ en erreur"},{"Revenus mensuels net *":"Entre 2500€ et 5000€","Préciser (€)":"$","message":"Champ en erreur"},{"Revenus mensuels net *":"Entre 2500€ et 5000€","Préciser (€)":"3000 €","message":"Champ en erreur"},{"Revenus mensuels net *":"Moins de 1500€","Préciser (€)":"\" 10\"","message":"Champ en erreur"},{"Revenus mensuels net *":"Moins de 1500€","Préciser (€)":"1000,2","message":"Champ en erreur"},{"Revenus mensuels net *":"Entre 1500€ et 2500€","Préciser (€)":"1803,5","message":"Champ en erreur"}])
			.then ('Le message bloquant apparaît', [{"Message":"Champ obligatoire Revenus mensuels net"},{"Message":"Champ en erreur"}])
			.and ('Les messages d\'erreurs sont sur fond rouge. Ils sont placés entre le bandeau bleu et la zone de contenu. Ils se ferment via petite croix en haut à droite de la zone d\'erreur. La fermeture du message se fait à l\'initiative de l\'utilisateur')
		.scenario('BDD technique')
			.given ('Je suis sur l\'écran "Connaissance Client", "5 Profession", "Vos revenus"')
			.when ('je regarde le code de la page')
			.then ('je constate que les id de champs sont bien conformes au tableau suivant :', [{"Enuméré":"CmbMontants_Revenu","Valeur":"RM1","Libellé":"Moins de 1 500 €"},{"Enuméré":"EnumereMontants_Revenu","Valeur":"RM2","Libellé":"Entre 1 500 € et 2 499 €"},{"Enuméré":"EnumereMontants_Revenu","Valeur":"RM3","Libellé":"Entre 2 500 € et 4 999 €"},{"Enuméré":"EnumereMontants_Revenu","Valeur":"RM4","Libellé":"Entre 5 000 € et 9 999 €"},{"Enuméré":"EnumereMontants_Revenu","Valeur":"RM5","Libellé":"Plus de 10 000 €"}])
})();