(function(){
	feature('AngularApp: Pour montrer l\'utilisation de specflow avec du JS et le fwk angular')
		.scenario('mseltjk (TestSet 1)')
			.given ('I enter "truc" into input')
			.when ('I press validate')
			.then ('the result stored must be "truc"')
		.scenario('mseltjk (TestSet 2)')
			.given ('I enter "truca" into input')
			.when ('I press validate')
			.then ('the result stored must be "truca"')
		.scenario('mseltjk (TestSet 3)')
			.given ('I enter "trucb" into input')
			.when ('I press validate')
			.then ('the result stored must be "trucb"')
		.scenario('mseltjk (TestSet 4)')
			.given ('I enter "trucc" into input')
			.when ('I press validate')
			.then ('the result stored must be "trucc"')
})();